version: '3.4'

services:
  ngapi:
    build: ./server
    image: cntrregistery.azurecr.io/ngapi
    command: 'node server.js'
    ports: 
        - "8090:80"
    volumes: 
        - ./server:/usr/src/app1
        - /usr/src/app1/node_modules

    
  ngapp:
    build: ./ngApp
    image: cntrregistery.azurecr.io/ngapp
    ports:
      - "8080:80"
    volumes: 
      - ./ngApp:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - ngapi

  # web:
  #   image: nginx:1.16.1-alpine
  #   volumes:
  #     - /usr/src/app/dist/ngApp:/usr/share/nginx/html
  #   ports:
  #     - "8080:80"
  #   environment: 
  #      - NGINX_HOST=localhost
  #      - NGINX_PORT=80
  #   command: [nginx-debug, '-g', 'daemon off;']
  #   depends_on:
  #      - ngapp